### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Rahaf-96** [GSG-K3/urban-calendar#66]
Add the following to the documentation:

- [x] Add Heroku link

- [x] Change Figma Design link.

- [x] How to create and build database locally.

- [x] Change database schema.

**Comment by Jood80** [comment]
@Rahaf-96 can't we just add the desktop version without removing the mobile design link?? since the later was absolutely a neat work and who knows maybe we can make it later on :muscle:

**Comment by Rahaf-96** [comment]
I totally agree with you :star_struck:  but maybe we can wait for Sara's thought too :thinking: @sara219
